# Generated by Django 2.2.7 on 2020-01-08 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200109_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Worker',
            field=models.ForeignKey(default=0, limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
