# Generated by Django 2.2.8 on 2020-08-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200109_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completetask',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='completetask',
            name='tasktype',
        ),
        migrations.AddField(
            model_name='completetask',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.worker'),
            preserve_default=False,
        ),
    ]
