# Generated by Django 2.2.8 on 2020-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200819_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
